project:
  name: HealthAI
  seed: 42
paths:
  data_dir: data
  artifacts_dir: artifacts
  models_dir: models
  logs_dir: logs
training:
  test_size: 0.2
  val_size: 0.1
  n_splits: 5
api:
  host: 0.0.0.0
  port: 8000 