version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
      target: production
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 60s

  ui:
    build:
      context: .
      dockerfile: docker/ui/Dockerfile
      target: production
    restart: always
    ports:
      - "8501:8501"
    environment:
      - ENVIRONMENT=production
      - API_BASE_URL=http://api:8000
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/healthz"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 60s

volumes:
  app_data:
