services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    platform: linux/amd64
    image: healthai-api
    ports:
      - "8000:8000"

  ui:
    build:
      context: .
      dockerfile: docker/ui/Dockerfile
    platform: linux/amd64
    image: healthai-ui
    environment:
      - API_BASE_URL=http://api:8000
    ports:
      - "8501:8501"
    depends_on:
      - api
